FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages

RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm --filter ./apps/telegram-miniapp build

FROM nginx:1.27-alpine
COPY apps/telegram-miniapp/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/telegram-miniapp/dist /usr/share/nginx/html

EXPOSE 8080
