FROM node:22-bookworm-slim
WORKDIR /app

ENV APP_PORT=3000

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY workers ./workers

RUN corepack enable
RUN pnpm install --frozen-lockfile --prod=false
RUN pnpm --filter ./workers/queue exec playwright install --with-deps chromium

ENV NODE_ENV=production

WORKDIR /app/apps/api

CMD ["node", "--import", "tsx", "./src/index.ts"]

EXPOSE 3000
