insert into playground_bot_definitions (
  bot_id,
  name,
  category,
  capability_manifest,
  source_binding,
  prompt_version,
  active
)
values
  (
    'document_wizard',
    'Document Wizard',
    'documents',
    '{"chat":true,"pdf_upload":true,"structured_form":true,"html_report":true}',
    'none',
    'phase-3-v1',
    true
  ),
  (
    'kb_concierge',
    'KB Concierge',
    'knowledge',
    '{"chat":true,"citations":true,"rag_query":true}',
    'knowledge_base',
    'phase-3-v1',
    true
  ),
  (
    'tutor',
    'Tutor',
    'learning',
    '{"chat":true}',
    'none',
    'phase-5-v1',
    true
  ),
  (
    'researcher',
    'Researcher',
    'research',
    '{"chat":true,"citations":true,"rag_query":true}',
    'knowledge_base',
    'phase-5-v1',
    true
  ),
  (
    'general_concierge',
    'General Concierge',
    'general',
    '{"chat":true}',
    'none',
    'phase-5-v1',
    true
  );
